name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Test
      run: dotnet test

    - name: Pack
      run: dotnet pack --configuration Release --no-restore

    - name: Publish Nuget package
      uses: myci-actions/publish-nuget@latest
      with:
        filename: "/bin/Release/FFXIVVenues.VenueModels.*.nupkg"
        api-key: "${{ secrets.NUGET_PAT }}"
        repo-url: "https://nuget.pkg.github.com/kana-ki/index.json"
