name: .NET

on:
  push:
    branches: [ main ]

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Test
      run: dotnet test
      
    - name: Pack
      run: dotnet pack --configuration Release --no-restore
      
    - name: Publish to NuGet.org source
      run: dotnet nuget push "FFXIVVenues.VenueModels/bin/Release/FFXIVVenues.VenueModels.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate

    - name: Configure GitHub source
      run: dotnet nuget add source --username kana-ki --password ${{ secrets.NUGET_REPO_PASSWORD }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/FFXIVVenues/index.json"
    
    - name: Publish to GitHub source
      run: dotnet nuget push "FFXIVVenues.VenueModels/bin/Release/FFXIVVenues.VenueModels.*.nupkg" --api-key ${{ secrets.NUGET_REPO_PASSWORD }} --source "github" --skip-duplicate
      
    - name: Publish to GitHub artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Nuget Package
        path: Kana.Pipelines/bin/Release/Kana.Pipelines.*.nupkg
